FROM registry.cn-hangzhou.aliyuncs.com/sakamoto/face-recog:0.1-cloudbuild

EXPOSE 10000

ADD .  /app

WORKDIR /app

ENV FLASK_APP=face_serve/face_recog_service.py \
    FLASK_ENV=production \
    FLASK_DEBUG=0 

ENTRYPOINT [ "python3" , "-m" , "flask" , "run" , "--host=0.0.0.0" , "--port=10000"] 